### ISSUE TITLE
Where is the Data Folder?

### ISSUE THREAD

**Issue by lovebdsobuj** [xebia/event-schedule-android#36]
Where is the data folder and Json files (Talk.json, Speaker.json, Slot.json, and Room.json)...?

**Comment by lovebdsobuj** [comment]
I gotten, here is https://github.com/ParsePlatform/ParseDeveloperDay

**Comment by lovebdsobuj** [comment]
But it's not working, what is actual `Talk.json, Speaker.json, Slot.json, and Room.json` file. 
Can I get from you??

Thank you.

**Comment by smuldr** [comment]
Hi! Sorry about the confusion, we split up the backend and frontend repositories and I forgot about those JSON files. I will pick this up as soon as possible.

**Comment by lovebdsobuj** [comment]
Thank you so much. I'm waiting for that.

I have a question about `FavoritesNotificationReceiver`.
# Favorites Item Notification get on by Schedule date?
